<?php
	$option_list_text = "Custom attribute";
	$Option_Manage_text = "Attribute Manage";//"属性管理";
	$Option_Manage_list = "Attribute List";//"属性列表";
	$text_or = "or";//"或";
	$website_name = "SQdish"; //"食器";
	$admin_center = "Management Center";//"管理中心";
	$website_text = "SQdish.com";//"食器 sqdish.com";
	$admin_info_text = "The administrator please note that save your account number, password, do not log in the background in public places";//"管理员请注意保存自己的帐号、密码，切勿在公共场合登录后台";
	$login_text = "Login";//"登录";
	$username_text = "Username";//"用户名";
	$psw_text = "Password";//"密码";
	$code_text = "Verification code";//"验证码";
	$forget_text = "Forget password please call 053275061";//"忘记密码请致电053 275 061";
	$BMC_text = "Administrator management center";//"后台管理中心";
	$index_text = "Home";//"首页";
	$search_text = "Search";//"搜索";
	$merchant_text = "Merchant list";//"商家列表";
	$add_text = "Add";//"新增";
	$delete_text = "Delete";//"删除";
	$export_text = "All export Excel";//"全部导出Excel";
	$name_text = "Name";//"名称";
	$name_text_thai = "Thai Name";//"泰语名称";
	$contact_text = "Contact information";//"联系方式";
	$contact_person_text = "Contact person";//"联系人";
	$admin_text = "Administrator";//"管理员";
	$QR_text = "QR code";//"二维码";
	$operation_type_name = "Category Name";//"分类名称";
	$operation_number = "Number";//"数量";
	$operation_text = "Operation";//"操作";
	$total_text = "Total ";//"共";
	$records_text = "Records";//"条记录";
	$new_menu_text = "New menu";//"新增菜单";
	$upload_new_menu_text = "Upload Menu";//"上传菜单";
	$upload_clear_menu_text = "Upload Menu Picture";//"请上传尽量清晰的菜单图片";
	$dishes_category = "Dishes Category"; //"菜品分类";
	$dishes_list = "Dishes List"; //"菜品列表";
	$menu_manage_text = "Menu management";//"菜单管理";
	$menu_download_text = "Menu download";//"菜单下载";
	$edit_text = "Edit";//"编辑";
	$merchant_manage_text = "Merchant manage";//"商家管理";
	$new_businesses_text = "New businesses";//"新增商家";
	$merchant_name_text = "Merchant name";//"商户名称";
	$merchant_address_text = "Merchant address";//商户地址
	$map_coordinates_text = "Map coordinates";//"地图坐标";
	$coordinate_text = "Coordinate";//"获取坐标";
	$share_information_text = "Share information";//"分享信息";
	$phone_text = "Phone";//"电话";
	$country_text = "Country";//"国家";
	$state_text = "State";//"省";
	$city_text = "City";//"市";
	$region_text = "Region";//"区";
	$referee_text = "Referee";//"推荐人";
	$intro_text = "Introduction";//"简介";
	$save_text = "Save";//"保存修改";
	$merchant_pic_text = "Merchant introduction picture (resolution: 800px by 420px)";//"商家介绍图片（分辨率：800px乘420px）";
	$upload_pic_text = "Upload pictures(only support JPG format images)";//"上传图片";
	$upload_pic_error = "Please do not upload files over 200K(only support JPG format images)";
	$select_file_text = "Select file";//"选择文件";
	$no_file_selected_text = "No file selected";//"未选择文件";
	$choose_file_text = "Choose the file to upload";//"请选择要上传的文件";
	$upload_success_text = "Upload successfully";//"上传成功";
	$dish_name_text = "Dish name";//"菜品名称";
	$dish_intro_text = "Brief introduction to dishes";//"菜品简介";
	$price_text = "Price";//"单价";
	$class_text = "Classification";//"分类";
	$recommend_text= "Recommend";//"推荐";
	$update_all = "Update all restaurant";//"更新所有餐厅";
	$update_all_alert = "Confirm the update?";//"确认更新吗？";
	$yes_text= "Yes";//"是";
	$no_text= "No";//"否";
	$attribute_control_text= "Attribute control";//"属性控制";
	$increase_attribute_text= "Increase attribute";//"增加属性";
	$attribute_list_text= "Attribute list";//"属性列表";
	$attribute_text= "Attribute";//"属性";
	$delete_attribute_text= "Delete this attribute";//"删除此属性";
	$add_option_text= "Add a new option";//"增加一个新选项";
	$option_ch_text= "Options for Chinese";//"选项中文";
	$option_thai_text= "Options for Thai";//"选项泰文";
	$option_price_text= "Option price";//"选项价格";
	$delete_option_text= "Delete this option";//"删除此选项";
	$dish_pic_text= "Dishes pictures (resolution / pixel: 600x600)";//"菜品图片（分辨率/像素：600x600）";
	$dish_menuPic_text= "Menu Picture";//"菜单图片";
	$pic_text= "Picture";//"图片";
	$order_meals_text= "Order of meals";//"点餐次数";
	$user_manage_text= "User management";//"用户管理 ";
	$add_user_text= "Add user";//"新增用户";
	$jurisdiction_text= "Jurisdiction";//"权限";
	$su_admin_text= "Super administrator";//"超级管理员";
	$re_admin_text= "Restaurant administrator";//"餐厅管理员";
	$user_list_text= "User list";//"用户列表";
	$recommended_number_text= "Recommended number";//"推荐数";
	$order_statistics_text= "Order statistics";//"点餐统计";
	$create_time_text= "Create time";//"创建时间";
	$restaurant_name_text= "Restaurant name";//"餐厅名称";
	$details_dishes_text= "Details of dishes";//"菜品详情";
	$total_price_text= "Total price";//"总价";
	$global_setting_text= "Global setting";//"全局设置";
	$rate_text= "1 baht RMB exchange rate";//"1泰铢兑换人民币汇率";
	$statistical_code_text= "Statistical code";//"统计代码";
	$exit_cancel_text= "Exit (cancel)";//"退出（注销）";
	$no_pic_alert = "Please upload pictures";//"请先上传图片！";
	$turnover_orders_text= "Turnover orders";//"成交订单";
	$yesterday_visit_text= "Yesterday visit";//"昨日访问";
	$active_business_text= "Active business";//"活跃商家";
	$system_announcement_text= "System announcement";//" 系统公告";
	$call_text= "Please call 053275061 after the information is uploaded";//"信息上传结束后请致电053 275 061";
	$common_text= "Some common modules";//"一些常用模块";
	$data_text= "Data";//"资料";
	$setup_text= "Set up";//"设置";
	$exti_text= "Exit";//"退出";
	$open_full_text= "Open full screen";//"开启全屏";
	$close_full_text= "Close full screen";//"关闭全屏";
	$language_text="Language";//"语言";
	$code_err_text="Verification code error";//"验证码错误";
	$login_err_text="User password error, please log in again";//"用户名密码错误，请重新登录";
	$input_chinese="Chinese";//"中文";
	$input_thai="Thai";//"泰文";
	$input_english ="English";//"英文";
	$doest_null ="Cannot be null";
	$rank_text = "Rank";
	$is_rec_text = "Recommend";//是否推荐
	$online_payment_text = "Online Payment";//在线支付
	//新增用户页面
	$useradd_restaurant_id="Restaurant id";//"餐厅ID";
	$useradd_FirstName="FirstName";//"用户名";
	$useradd_Surname="SurName";//"用户姓";
	$useradd_Position="Position";//"职务";
	$useradd_Manager="Manager";//"经理";
	$useradd_Owner="Owner";//"餐厅所有者";
	$useradd_Birthday="Birthday";//"生日";
	$confirm_del_text = "Are you deleting? (once deleted)";//"是否删除？（一经删除无法恢复）";
	//菜品翻译
	$Translate_Manage="Translate Manage";//"菜品翻译管理";
	$batch_deletion="Batch Deletion";//"批量删除";
	$Edit_Dishes_Translation="Edit Dishes Translation";//"编辑菜品翻译";
	//内容管理
	$cms_article_text = "CMS System";//内容管理系统";
	$add_article_text = "Add New Article";//新增文章";
	$edit_article_text = "Edit Article";//编辑文章";
	$article_type_text = "Article Category";//"文章分类";
	$keywords_admin_text = "Keywords Administration";//"关键词管理";
	$article_pic_text = "Article thumbnail（Resolution：309px × 146px）";//"文章缩略图（分辨率：**px乘**px）";
	$article_title_text = "Article Title";//"文章标题";
	$article_category_text = "Article Category";//"文章分类";
	$article_author_text = "Author";//"作者";
	$article_click_text = "Click";//"点击数";
	$article_keywords_text = "Keywords";//"关键词";
	$author_recommend_text = "Editing recommend";//"编辑推荐";
	$author_recommend_new_text = "New recommend";//"新增推荐";
	$author_recommend_title_text = "Recommend title";//"推荐内容标题";
	$author_recommend_url_text = "Recommend Url";//"推荐内容链接";
	$article_keywords_tips =  "English“ ,” comma separated, not more than 3";//"英文“ ,”逗号隔开，不要超过3个";
	$article_des_text = "escription";//"简介";
	$article_des_trips_text = "Automatically intercept the first 80 characters of the text";//"为空将自动截取正文前80个字符";
	$article_recommend_text = "Recommend";//"推荐";
	$article_recommend_pic = "Recommended pictures（Resolution：200px × 280px）";//"推荐配图";
	$article_recommend_pic2 = "แนะนำงาน(Resolution :248px × 106px)";//"推荐配图2";
	$article_article_recommend_pic_tips = "Resolution：**px × **px";//"分辨率：**px乘**px";
	$article_alink_text = "Hypertext";//"锚文本";
	$article_fakeOriginal_text = "Fake original";//"伪原创";
	$article_body = "Content text";//"内容正文";
	$edit_article_recommend_text = "Edit Article Recommend";//"编辑推荐";
	$continue_edit_article_recommend_text = "Continue Edit Article Recommend";//"继续编辑推荐";
	//--文章列表
	$list_article_text = "Articles List";//文章列表";
	$article_ecommend_manage = "Article Rcommend Manage";//"编辑推荐管理";
	//--文章分类
	$article_category_name_text = "Category name";//"分类名称";
	$category_add_edit_text = "Category new / edit";//"分类新增/编辑";
	$article_category_keyword_text = "Article Category Keywords";//"分类关键词";
	$article_category_desc_text = "Article Category Escription";//分类描述";
	//--关键词管理
	$keyword_add_edit_text = "Keywords new / edit";//"关键词新增/编辑";
	$article_keyword_name_text = "Keywords name";//"关键词名称";
	$article_keywordsUrl_text = "Keywords link";//关键词链接" ;
	$article_keywordsNum_text = "Keywords weight";//"关键词权重" ;
	//自定义管理
	$icon_service_text = "Custom icon";//"自定义图标";
	$icon_text ="Icon";//图标;
	$icon_name_text = "Icon Name";//图标名称
	$edit_icon_text ="Edit icon";//"编辑图标";
	$add_icon_text ="Add icon";//"新增图标";
	$restaurant_type_text="Restaurant Type";//餐厅类型
	$custom_type_text = "Custom Type";//自定义分类
	$custom_type_name_text = "Custom Type Name";//分类名称
	$is_on_text = "Whether To Open";//是否开启
	$add_type_text  = "Add Type";//新增分类
	$select_icon_text = "Select Icon";//选择图标 
	$edit_type_text = "Edit Type";//编辑分类
	$email_text ="Email";//邮箱
	$business_hour_text ="Business Hour";//营业时间
	$required_QRcode_number_text = "The Required Number Of QRcode";//所需二维码数量
	$tip_title_text = "Please read carefully before uploading";
	$tip_content_text ="1.The restaurant dishes except drinks, Steamed Rice external demand more than 20 dishes, coffee, rice noodles shop, no menu of the restaurant is not in the scope of cooperation;<br />2.Before uploading the following information, the person in charge of the restaurant has been authorized to permit;<br />3.Ensure the true and effective validity of the uploaded information;";
	$audit_status_text="Audit Status";//审核状态
	$pending_audit_text ="Pending Audit";//待审核
	$pass_audit_text = "Pass Audit";//已通过
	$no_audit_text = "Not Pass Audit";//未通过
	$no_audit_reason_text ="Reason Of Fail";//未通过原因
	$error_tip_text ="Please fill out the details without the reason, we will give the feedback to the recommendation.";//错误信息
	$reg_time_text ="Registration Time";//注册时间
	$warning_text ="Warning: please carefully review the business information and user information, if the information is correct please click through the button, the user background dishes management will be opened, we will send the details to the user's mailbox, if the information is incorrect or incomplete, please click on the button, and fill in the reasons, we will inform the recommendation, modify the information, re audit.";//警告
	$merchant_information_text="Merchant Information";//商家信息
	$user_information_text = "User Information";//用户信息
	$email_manage_text ="Email Manage";//邮件管理
	$write_email_text = "Write Email";//写邮件
	$email_list_text ="Mailing List";//邮件列表
	$email_title_text = "Email Title";//邮件标题
	$addresser_text = "Addresser";//发件人
	$email_classifiction_text ="Classification Of Mail";//邮件分类
	$system_email_text = "System Email";//系统邮件
	$private_email_text ="Private Email";//私人邮件
	$addressee_text ="Addressor";//收件人
	$please_write = "Please fill out";//请填写
	$repeat_text = "Repeat";//重复
	$be_outside_the_law ="be outside the law";//不合法
	$choose_text = "Please select";//请选择
	$next_city_text = "Subordinate city";//下级城市
	$Thailand = "Thailand";
	$reg_text = "Register";//注册
	//优惠券管理
	$coupon_type = "Coupon Type";//"优惠券类型";
	$coupon_number = "Coupon Number";//"优惠券数量";
	$coupon_list = "Coupon list";//优惠券列表
	$coupon_list_paper = "Paper Coupon list";//优惠券管理
	$coupon_digital = "Electronic Coupon";//"电子优惠券";
	$coupon_paper = "Paper Coupon";//"纸质优惠券";
	$manage_coupon_text = "Coupon Management";//优惠券管理
	$add_coupon_text = "Add Coupon";//新增优惠券
	$coupon_name_text = "Coupon Name";//优惠券名称
	$coupon_amount_used = "Used（sheet）";//剩余数量（张）
	$coupon_pic_text = "Coupon Image（resolution ratio：600x600）";//优惠券图片（分辨率/像素：600x600）
	$coupon_intro_text = "Coupon instructions";//优惠券使用说明
	$coupon_amount_text = "Quantity";//数量
	$coupon_use_text = "Coupon Usage";//优惠券兑换
	$coupon_code_text = "Coupon Verification Code";//优惠券验证码
	$coupon_status_text = "Coupon Status";//优惠券使用情况
	$coupon_exchange_text = "Coupon Usage Attention:";//优惠券兑换操作说明：
	$coupon_exchange_content = "In order to use the coupon, please enter the coupon verification code from the customer to the left side input box.";//优惠券兑换说明
	$coupon_submit = "Submit";//兑换
	$coupon_submit_success = "Submit Success";
	$coupon_buy_time = "buy time";//购买时间
	$coupon_use_time = "use time";//使用时间
	$coupon_status = "status";//状态
	$coupon_used = "used";//已使用
	$coupon_unused = "not used";//未使用
	$coupon_fail = "Validation failure,Please enter the correct coupon verification code.";//验证失败，请输入正确的优惠券验证码！
	$coupon_deadline = "Deadline";//截止日期
	$coupon_overdue = "The coupon has expired.";//该优惠券已过期
	//表单验证
	$requried_text = "Requried";//必填项
	$please_check_detele_text = "Please select the option to delete";//请选择要删除的选项
	$member_manager_text = "Member Management";//会员管理
	$member_list_text = "Member List";//会员列表
	$nickname_text = "nickname";//昵称
	$order_manager_text = "Order Management";//订单管理
	$order_list_text = "Order List";//订单列表
	$reg_way_text = "Registration Approach";//注册途径
	$upload_avatar = "Upload Avatar";//上传头像
	$wechat_text = "WeChat";//微信
	$order_num_text = "Order No.";
	$pay_status_text = "Payment Status";//支付状态
	$done_status_text = "Settlement Status";//结算状态
	$money_text = "Amount Of Money";
	$details_text = "Details";//详情
?>