<?php
	$option_list_text = "กำหนดประเภทเอง";
	$Option_Manage_text = "ระบบการจัดการคุณสมบัติ";//"属性管理";
	$Option_Manage_list = "รายชื่อคุณสมบัติ";//"属性列表";
	$text_or = "หรือ";//"或";
	$website_name = "SQdish"; //"食器";
	$admin_center = "ระบบการจัดการ";//"管理中心";
	$website_text = "sqdish.com";//"食器 sqdish.com";
	$admin_info_text = "ผู้ดูแลโปรดละมัดระวังในการเก็บรักษาชื่อผู้ใช้ รหัสผ่าน ของตัวเอง ไม่ควรนำไปใช้งานในที่สาธารณะ ";//"管理员请注意保存自己的帐号、密码，切勿在公共场合登录后台";
	$login_text = "ลงทะเบียน";//"登录";
	$username_text = "ชื่อผู้เข้าใช้";//"用户名";
	$psw_text = "รหัสผ่าน";//"密码";
	$code_text = "รหัสรักษาความปลอดภัย";//"验证码";
	$forget_text = "ลืมรหัสผ่าน โปรดติดต่อ 053-275-061";//"忘记密码请致电053 275 061";
	$BMC_text = "ระบบการจัดการหลังบ้าน";//"后台管理中心";
	$index_text = "หน้าหลัก";//"首页";
	$search_text = "ค้นหา";//"搜索";
	$merchant_text = "รายชื่อร้านอาหาร";//"商家列表";
	$add_text = "เพิ่ม";//"新增";
	$delete_text = "ลบ";//"删除";
	$export_text = "ดาวโหลดเป็นExcel";//"全部导出Excel";
	$name_text = "ชื่อร้านอาหาร";//"名称";
	$name_text_thai = "ชื่อภาษาไทย";//"泰语名称";
	$contact_text = "เบอร์โทรติดต่อ";//"联系方式";
	$contact_person_text = "บุคคลที่ติดต่อ";//"联系人";
	$admin_text = "พนักงานผู้ดูแล";//"管理员";
	$QR_text = "QR code";//"二维码";
	$operation_type_name = "ชื่อประเภทอาหาร";//"分类名称";
	$operation_number = "จำนวน";//"数量";
	$operation_text = "การดำเนินงาน";//"操作";
	$total_text = "มีทั้งหมด";//"共";
	$records_text = "ร้านบนระบบ";//"条记录";
	$new_menu_text = "เพิ่มรายการอาหารใหม่";//"新增菜单";
	$upload_new_menu_text = "อัพโหลดรายการอาหาร";//"上传菜单";
	$upload_clear_menu_text = "กรุณาอัพโหลดรูปภาพอาหารที่ชัดเจน";//"请上传尽量清晰的菜单图片";
	$dishes_category = "แบ่งประเภทอาหาร"; //"菜品分类";
	$dishes_list = "ตารางรายการอาหาร"; //"菜品列表";
	$menu_manage_text = "การจัดการรายการอาหาร";//"菜单管理";
	$menu_download_text = "ดาวโหลดรายการอาหาร";//"菜单下载";
	$edit_text = "แก้ไข";//"编辑";
	$merchant_manage_text = "การจัดการร้านค้า";//"商家管理";
	$new_businesses_text = "เพิ่มร้าน-กิจการใหม่";//"新增商家";
	$merchant_name_text = "ชื่อร้าน-กิจการ";//"商户名称";
	$merchant_address_text = "ที่อยู่ธุรกิจ";//商户地址
	$map_coordinates_text = "พิกัดบนแผนที่";//"地图坐标";
	$coordinate_text = "ค้นหาพิกัดร้าน";//"获取坐标";
	$share_information_text = "แชร์ข้อมูล";//"分享信息";
	$phone_text = "เบอร์โทรติดต่อ";//"电话";
	$country_text = "ประเทศ";//"国家";
	$state_text = "จังหวัด";//"省";
	$city_text = "เมือง";//"市";
	$region_text = "โซน";//"区";
	$referee_text = "บุคคลที่แนะนำ";//"推荐人";
	$intro_text = "แนะนำ";//"简介";
	$save_text = "บันทึก";//"保存修改";
	$merchant_pic_text = "รูปแนะนำของกิจการ(ความละเอียด :800px คูณ 420px)";//"商家介绍图片（分辨率：800px乘420px）";
	$upload_pic_text = "อัพโหลดรูปภาพ(และควรใช้รูปสกุลjpgในการอัพโหลด)";//"上传图片";
	$select_file_text = "เลือกไฟส์";//"选择文件";
	$no_file_selected_text = "ยังไม่ได้เลือกไฟส์";//"未选择文件";
	$choose_file_text = "โปรดเลือกไฟส์ที่จะอัพโหลด";//"请选择要上传的文件";
	$upload_pic_error = "ไม่ควรอัพโหลดรูปที่มีขนาดเกิน200KB(และควรใช้รูปสกุลjpgในการอัพโหลด)";//"请不要上传超过200k的文件(仅支持JPG格式的图片)";
	$upload_success_text = "อัพโหลดสำเร็จ";//"上传成功";
	$dish_name_text = "ชื่ออาหาร";//"菜品名称";
	$dish_intro_text = "แนะนำรายการอาหาร";//"菜品简介";
	$price_text = "ราคา";//"单价";
	$class_text = "ประเภท";//"分类";
	$recommend_text= "แนะนำ";//"推荐";
	$update_all = "อัพเดทข้อมูลร้านอาหารทั้งหมด";//"更新所有餐厅";
	$update_all_alert = "ให้แน่ใจว่าปรับปรุง ? ";//"确认更新吗？";
	$yes_text= "ใช่";//"是";
	$no_text= "ไม่ใช่";//"否";
	$attribute_control_text= "ควบคุมคุณสมบัติ";//"属性控制";
	$increase_attribute_text= "เพิ่มคุณสมบัติ";//"增加属性";
	$attribute_list_text= "รายการคุณสมบัติ";//"属性列表";
	$attribute_text= "คุณสมบัติ";//"属性";
	$delete_attribute_text= "ลบคุณสมบัติ";//"删除此属性";
	$add_option_text= "เพิ่ม1รายการการเลือก";//"增加一个新选项";
	$option_ch_text= "รายการการเลือกภาษาจีน";//"选项中文";
	$option_thai_text= "รายการการเลือกภาษาจีน";//"选项泰文";
	$option_price_text= "ราคารายการการเลือก";//"选项价格";
	$delete_option_text= "ลบรายการการเลือกดังกล่าว";//"删除此选项";
	$dish_pic_text= "รูปอาหาร(ความละเอียด:600 คูณ 600)";//"菜品图片（分辨率/像素：600x600）";
	$dish_menuPic_text= "รูปเมนู";//"菜单图片";
	$pic_text= "รูปภาพ";//"图片";
	$order_meals_text= "จำนวนครั้งในการสั่งอาหาร";//"点餐次数";
	$user_manage_text= "การจัดการสำหรับเจ้าของกิจการ";//"用户管理 ";
	$add_user_text= "เพิ่มผู้ใช้ใหม่";//"新增用户";
	$jurisdiction_text= "สิทธิ์ของผู้ใช้";//"权限";
	$su_admin_text= "ผู้จัดการระบบ";//"超级管理员";
	$re_admin_text= "ผู้จัดการในกิจการ";//"餐厅管理员";
	$user_list_text= "รายชื่อผู้ใช้งาน";//"用户列表";
	$recommended_number_text= "จำนวนครั้งที่แนะนำ";//"推荐数";
	$order_statistics_text= "สถิติการสั่งอาหาร";//"点餐统计";
	$create_time_text= "เวลาในการใช้งาน";//"创建时间";
	$restaurant_name_text= "ชื่อร้านอาหาร";//"餐厅名称";
	$details_dishes_text= "รายละเอียดอาหาร";//"菜品详情";
	$total_price_text= "ราคารวม";//"总价";
	$global_setting_text= "ตั้งค่าตามสถาณการณ์โลก";//"全局设置";
	$rate_text= "ราคาเงินบาทแลกเงินหยวน";//"1泰铢兑换人民币汇率";
	$statistical_code_text= "ตัวเลขสถิติ";//"统计代码";
	$exit_cancel_text= "ลงชื่อออก";//"退出（注销）";
	$no_pic_alert = "กรุณาอัพโหลดรูปภาพ";//"请先上传图片！";
	$turnover_orders_text= "สั่งอาหารเสร็จ";//"成交订单";
	$yesterday_visit_text= "จำนวนผู้เข้าเยี่ยมชม(เมื่อวาน)";//"昨日访问";
	$active_business_text= "กิจการบนระบบ";//"活跃商家";
	$system_announcement_text= "ประกาศจากระบบ";//" 系统公告";
	$call_text= "หลังจากอัพโหลดข้อมูลเสร็จแล้ว กรุณาติดต่อ053 275 061";//"信息上传结束后请致电053 275 061";
	$common_text= "รูปแบบที่พบบ่อย";//"一些常用模块";
	$data_text= "ข้อมูล";//"资料";
	$setup_text= "ตั้งค่า";//"设置";
	$exti_text= "ออกจากระบบ";//"退出";
	$open_full_text= "เปิดเต็มหน้าจอ";//"开启全屏";
	$close_full_text= "ปิดการเปืดเต็มหน้าจอ";//"关闭全屏";
	$language_text="ภาษา";//"语言";
	$code_err_text="รหัสตรวจสอบข้อผิดพลาด";//"验证码错误";
	$login_err_text="ชื่อผู้ใช้รหัสผ่านไม่ถูกต้องกรุณาเข้าสู่ระบบอีกครั้ง";//"用户名密码错误，请重新登录";
	$input_chinese="ภาษาจีน";//"中文";
	$input_thai="ภาษาไทย";//"泰文";
	$input_english="ในภาษาอังกฤษ";//"英文";
	$doest_null ="จะว่างเปล่า";
	$rank_text = "เรียงลําดับ";
	$is_rec_text = "ว่าจะแนะนำ";//是否推荐
	$online_payment_text = "การชำระเงินออนไลน์";//在线支付
	//新增用户页面
	$useradd_restaurant_id="รหัสร้าน ID";//"餐厅ID";
	$useradd_FirstName="ชื่อผู้ใช้";//"用户名";
	$useradd_Surname="นามสกุลผู้ใช้";//"用户姓";
	$useradd_Position="ตำแหน่ง";//"职务";
	$useradd_Manager="ผู้จัดการ";//"经理";
	$useradd_Owner="เจ้าของกิจการ";//"餐厅所有者";
	$useradd_Birthday="วันเกิด";//"生日";
	$confirm_del_text = "คุณกำลังลบ ? ( ลบครั้ง )";//"是否删除？（一经删除无法恢复）";
	//菜品翻译
	$Translate_Manage="ระบบแปลเมนูภาษาไทย";//"菜品翻译管理";
	$batch_deletion="ลบที่เลือก";//"批量删除";
	$Edit_Dishes_Translation="แก้ไขคำแปล";//"编辑菜品翻译";
	//内容管理
	$cms_article_text = "การจัดการเนื้อหา";//内容管理系统";
	$add_article_text = "บทความใหม่";//新增文章";
	$edit_article_text = "แก้ไขบทความ";//编辑文章";
	$article_type_text = "การจัดหมวดหมู่บทความ";//"文章分类";
	$keywords_admin_text = "การบริหารจัดการ";//"关键词管理";
	$article_pic_text = "ภาพที่โพสต์(ความละเอียด:309px × 146px)";//"文章缩略图（分辨率：**px乘**px）";
	$article_title_text = "ชื่อเรื่องของบทความนี้";//"文章标题";
	$article_category_text = "การจัดหมวดหมู่บทความ";//文章分类";
	$article_author_text = "ผู้เขียน";//"作者";
	$article_click_text = "点击数";//"点击数";
	$article_keywords_text = "คำสำคัญ :";//"关键词";
	$author_recommend_text = "บรรณาธิการแนะนำ";//"编辑推荐";
	$author_recommend_new_text = "แนะนำใหม่";//"新增推荐";
	$author_recommend_title_text = "แนะนำเนื้อหาชื่อเรื่อง";//"推荐内容标题";
	$author_recommend_url_text = "แนะนำเนื้อหาที่เชื่อมโยง";//"推荐内容链接";
	$article_keywords_tips =  "คั่นด้วยเครื่องหมายจุลภาคในภาษาอังกฤษไม่เกิน 3 .";//"英文“ ,”逗号隔开，不要超过3个";
	$article_des_text = "บรรยาย";//"简介";
	$article_des_trips_text = "โดยอัตโนมัติจะสกัดกั้นว่างเปล่าก่อนข้อความ 80 ตัวอักษร";//"为空将自动截取正文前80个字符";
	$article_recommend_text = "แนะนำ";//"推荐";
	$article_recommend_pic = "แนะนำงาน(ความละเอียด:200px × 280px)";//"推荐配图";
	$article_recommend_pic2 = "แนะนำงาน(ความละเอียด:248px × 106px)";//"推荐配图2";
	$article_article_recommend_pic_tips = "ความละเอียด:px** × px**";//"分辨率：**px乘**px";
	$article_alink_text = "ข้อความจุดยึด";//"锚文本";
	$article_fakeOriginal_text = "สิ่งประดิษฐ์ต้นฉบับ";//"伪原创";
	$article_body = "เนื้อหาของบทความ";//"内容正文";
	$edit_article_recommend_text = "บรรณาธิการแนะนำ";//"编辑推荐";
	$continue_edit_article_recommend_text = "แนะนำให้แก้ไข";//"继续编辑推荐";
	//--文章列表
	$list_article_text = "รายการบทความ";//文章列表";
	$article_ecommend_manage = "บรรณาธิการแนะนำการจัดการ";//"编辑推荐管理";
	//--文章分类
	$article_category_name_text = "ชื่อหมวดหมู่";//"分类名称";
	$category_add_edit_text = "จัดหมวดหมู่ใหม่ / แก้ไข";//"分类新增/编辑";
	$article_category_keyword_text = "ประเภทของคําสําคัญ";//"分类关键词";
	$article_category_desc_text = "รายละเอียด";//分类描述";
	//--关键词管理
	$keyword_add_edit_text = "คำหลักใหม่ / แก้ไข";//"关键词新增/编辑";
	$article_keyword_name_text = "คำหลักในชื่อ";//"关键词名称";
	$article_keywordsUrl_text = "คำหลักที่จะเชื่อมโยง";//"关键词链接" ;
	$article_keywordsNum_text = "น้ำหนักคำหลัก";//"关键词权重" ;
	//自定义管理
	$icon_service_text = "ไอคอนที่กําหนดเอง";//"自定义图标"
	$icon_text ="ไอคอน";//图标
	$icon_name_text = "ชื่อของไอคอน";//图标名称
	$edit_icon_text ="ไอคอนแก้ไข";//"编辑图标";
	$add_icon_text ="เพิ่มไอคอน";//"新增图标";
	$restaurant_type_text = "ประเภทร้านอาหาร";//餐厅类型
	$custom_type_text = "การจัดประเภทแบบกําหนดเอง";//自定义分类
	$custom_type_name_text  = "ชื่อหมวดหมู่";//分类名称
	$is_on_text ="ว่าจะเปิด";//是否开启
	$add_type_text  = "หมวดหมู่ใหม่";//新增分类
	$select_icon_text = "เลือกไอคอน";//选择图标
	$edit_type_text = "แก้ไขหมวดหมู่";//编辑分类
	$email_text ="อีเมล์";//邮箱
	$business_hour_text = "ชั่วโมงธุรกิจ";//营业时间
	$required_QRcode_number_text ="จํานวนที่ต้องการรหัสสองมิติ";//所需二维码数量
	$tip_title_text ="กรุณาอ่านก่อนการอัปโหลด";//上传前请仔细阅读
	$tip_content_text ="1.นอกจากข้าวและเครื่องดื่ม เป็นอาหารที่ต้องมี 20 ร้านกาแฟ , ก๋วยเตี๋ยว , ร้านไม่มีเมนูของทางร้านไม่ได้อยู่ในขอบเขตของความร่วมมือ;<br />2.ในการอัพโหลดข้อมูลต่อไปนี้ก่อนที่จะได้รับอนุญาตจากผู้ที่รับผิดชอบได้ร้านอาหาร;<br />3.รับประกันความถูกต้องของข้อมูลที่อัปโหลดโดยชอบด้วยกฎหมาย";
	$audit_status_text ="สถานะของการตรวจสอบ";//审核状态
	$pending_audit_text = "การตรวจสอบ";//待审核
	$pass_audit_text = "ผ่านการตรวจสอบ";//已通过
	$no_audit_text ="ไม่ต้องผ่าน";//未通过
	$no_audit_reason_text ="เหตุผลที่ไม่ได้ผ่าน";//未通过原因
	$error_tip_text ="กรุณากรอกรายละเอียดเหตุผลที่ไม่ได้ผ่านเราก็จะส่งข้อมูลกลับไปที่แนะนำสำหรับคน";//错误信息
	$reg_time_text ="เวลาลงทะเบียน";//注册时间
	$warning_text = "คำเตือน : โปรดตรวจสอบข้อมูลทางธุรกิจและข้อมูลผู้ใช้หากข้อมูลที่ผ่านการตรวจสอบที่ถูกต้องให้คลิกปุ่มที่ผู้ใช้การจัดการพื้นหลังเมนูจะเปิดเราก็จะใส่รายละเอียดข้อมูลที่ส่งในกล่องจดหมายของผู้ใช้หากข้อมูลที่ไม่ถูกต้องหรือไม่สมบูรณ์และคลิกที่ปุ่มและกรอกข้อมูลในแบบฟอร์มที่ไม่ผ่านและไม่ผ่านด้วยเหตุผลที่ว่าเราจะบอกเหตุผลแนะนำคนเพื่อตรวจสอบ";//警告
	$merchant_information_text ="ข้อมูลทางธุรกิจ";//商家信息
	$user_information_text ="ข้อมูลผู้ใช้";//用户信息
	$email_manage_text = "ผู้จัดการจดหมาย";//邮件管理
	$write_email_text = "เขียนจดหมาย";//写邮件
	$email_list_text = "รายชื่อผู้รับจดหมาย";//邮件列表
	$email_title_text = "ส่วนหัวของข้อความ";//邮件标题
	$addresser_text = "ผู้ส่ง";//发件人
	$email_classifiction_text ="การจัดข้อความ";//邮件分类
	$system_email_text = "จดหมายของระบบ";//系统邮件
	$private_email_text ="ส่วนตัว";//私人邮件
	$addressee_text ="ผู้รับ";//收件人
	$please_write = "กรุณากรอกข้อมูล";//请填写
	$repeat_text="ซ้ำ";//重复
	$be_outside_the_law ="ไม่ชอบด้วยกฎหมาย";//不合法
	$choose_text = "กรุณาเลือก";//请选择
	$next_city_text = "ของเมือง";//城市
	$Thailand = "ประเทศไทย";
	$reg_text = "การลงทะเบียน";//注册
	//优惠券管理
	$coupon_type = "ประเภทของคูปอง";//"优惠券类型";
	$coupon_number = "จำนวนคูปอง";//"优惠券数量";
	$coupon_list = "รายชื่อตราสาร";//优惠券列表
	$coupon_list_paper = "คูปองกระดาษ";//优惠券列表
	$coupon_digital = "คูปองอิเล็กทรอนิกส์";//"电子优惠券";
	$coupon_paper = "คูปองกระดาษ";//"纸质优惠券";
	$manage_coupon_text = "คูปองการจัดการ";//优惠券管理
	$add_coupon_text = "คูปองใหม่";//新增优惠券
	$coupon_name_text = "คูปองชื่อ";//优惠券名称
	$coupon_amount_used = "จำนวนที่เหลือ";//剩余数量
	$coupon_pic_text = "แนะนำงาน(ความละเอียด:：600x600)";//推荐配图
	$coupon_intro_text = "คำแนะนำในการใช้คูปอง";//优惠券使用说明
	$coupon_amount_text = "จํานวน";//数量
	$coupon_use_text = "คูปองแลกเปลี่ยน";//优惠券兑换
	$coupon_code_text = "รหัสยืนยัน";//优惠券验证码
	$coupon_status_text = "เงื่อนไขการใช้คูปอง";//优惠券使用情况
	$coupon_exchange_text = "คูปองแลกเปลี่ยนการแนะนํา";//优惠券兑换操作说明：
	$coupon_exchange_content = "กรุณาป้อนรหัสยืนยันที่ลูกค้าจะแสดงช่องใส่คูปองเงินสดใช้ไปด้านซ้าย";//优惠券兑换说明
	$coupon_submit = "ส่ง";//兑换
	$coupon_submit_success = "ความสำเร็จในการแลกเปลี่ยน";
	$coupon_buy_time = "เวลาที่จะซื้อ";//购买时间
	$coupon_use_time = "เวลาที่ใช้";//使用时间
	$coupon_status = "สถานะ";//状态
	$coupon_used = "มีการใช้";//已使用
	$coupon_unused = "ไม่ได้ใช้";//未使用
	$coupon_fail = "ล้มเหลวในการตรวจสอบ，กรุณาป้อนรหัสคูปองที่ถูกต้อง！";//验证失败，请输入正确的优惠券验证码！
	$coupon_deadline = "สิ้นสุดวันที่";//截止日期
	$coupon_overdue = "คูปองนี้หมดอายุแล้ว";//该优惠券已过期
	//表单验证
	$requried_text = "ที่จําเป็น";//必填项
	$please_check_detele_text = "โปรดเลือกตัวเลือกที่คุณต้องการลบ";//请选择要删除的选项
	$member_manager_text = "การจัดการสมาชิก";//会员管理
	$member_list_text = "รายชื่อสมาชิก";//会员列表
	$nickname_text = "ชื่อเล่น";//昵称
	$order_manager_text = "การบริหารการสั่งซื้อ";//订单管理
	$order_list_text = "รายการสั่งซื้อ";//订单列表
	$reg_way_text = "วิธีลงทะเบียน";//注册途径
	$upload_avatar = "อัปโหลดไอคอน";//上传头像
	$wechat_text = "WeChat";//微信
	$order_num_text = "หมายเลขการสั่งซื้อ";//订单号
	$pay_status_text = "สถานะการจ่ายเงิน";//支付状态
	$done_status_text = "ของรัฐสำหรับ";//结算状态
	$money_text = "จํานวนเงิน";//金额
	$details_text = "สำหรับรายละเอียดเพิ่มเติม";//详情
?>